// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxxzeiswnzloxukogory.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4eHplaXN3bnpsb3h1a29nb3J5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NTEyNTMsImV4cCI6MjA3MTEyNzI1M30.T9C7qXX6xor9peTTHQ-7PtGVQGPbcitvz8O3aASRfgI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
